name: 'Testing'

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.3
        with_wrapper: false

    - name: Init Basic
<<<<<<< Updated upstream
      run: cd examples/basic && terraform init
=======
      run: cd examples/basic && terraform init -upgrade
>>>>>>> Stashed changes

    - name: Validate Basic
      run: cd examples/basic && terraform validate